### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by amireh** [0xTeles/syngql-security#1]
Hi Teles and thank you for your interest in SYNG! As you might know, the software is currently in beta, and I'd love to hear about your experience and any feedback you might have regarding the query language or the tool in general. If you'd like, we can use this thread or the [Discord server](https://discord.gg/ZUGAM9Y23r) to talk more closely. Let me know.

**Comment by 0xTeles** [comment]
Hi @amireh. Of course, I"ll do. Thanks for the tool <3

**Comment by amireh** [comment]
Great, and welcome!
